version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management plugin port
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Ecommerce
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,Z
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
